# Copyright 2022 DeepMind Technologies Limited.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# proto-file: android_env/proto/task.proto
# proto-message: android_env.Task

id: "sgtpuzzles_blackbox_10x10_5_balls"
name: "Simon Tatham's puzzle - Blackbox - 10x10 - 5 Balls"
description: "Determine where the hidden balls are in the box, by observing the behaviour of light beams fired into the box from the sides. Click in a square around the edge of the box to send a beam into the box."

setup_steps: [
  {
    adb_request: {
      install_apk: {
        filesystem: {
          path: "2020.07.08-sgtpuzzles-debug.apk"
        }
      }
    }
    success_condition: {
      check_install: {
        package_name: "name.boyle.chris.sgtpuzzles"
        timeout_sec: 10.0
      }
    }
  },
  {  # Put the device in portrait mode.
    adb_request: {
      settings: {
        name_space: SYSTEM
        put: { key: "user_rotation" value: "0" }
      }
    }
  }
]

reset_steps: [
  { adb_request: { force_stop: { package_name: "name.boyle.chris.sgtpuzzles" } } },
  { adb_request: { package_manager: { clear: { package_name: "name.boyle.chris.sgtpuzzles" } } } },
  {
    adb_request: {
      start_activity: {
        force_stop: true
        full_activity: "name.boyle.chris.sgtpuzzles/name.boyle.chris.sgtpuzzles.SGTPuzzles"
        extra_args: [
            "--ez", '"RL_TASK_ENABLED"', '"true"',
            # params: w{width}h{height}m{minimum}M{maximum}
            "--es", '"RL_TASK_GAME_CONFIG"', '"{ \\"gameId\\":\\"blackbox\\",\\"params\\":\\"w10h10m5M5\\"}"'
        ]
      }
    }
    success_condition: {
      wait_for_app_screen: {
        app_screen: {
          activity: "name.boyle.chris.sgtpuzzles/name.boyle.chris.sgtpuzzles.GamePlay"
          view_hierarchy_path: [
          ]
        }
        timeout_sec: 10.0
      }
      num_retries: 10
    }
  },
  {
    adb_request: {
      start_screen_pinning: {
        full_activity: "name.boyle.chris.sgtpuzzles/name.boyle.chris.sgtpuzzles.GamePlay"
      }
    }
  }
]

expected_app_screen: {
  activity: "name.boyle.chris.sgtpuzzles/name.boyle.chris.sgtpuzzles.GamePlay"
  view_hierarchy_path: [
  ]
}

max_episode_sec: 7200  # Prevent infinite episodes.

log_parsing_config: {

  filters: ["AndroidRLTask:V"]

  log_regexps: {
    score: "^[Ss]core: ([-+]?[0-9]*\\.?[0-9]*)$"
    reward: "^[Rr]eward: ([-+]?[0-9]*\\.?[0-9]*)$"
    episode_end: "^episode[ _]end$"
    extra: "^extra: (?P<name>[^ ]*)[ ]?(?P<extra>.*)$"
    json_extra: "^json_extra: (?P<json_extra>.*)$"
  }
}

extras_spec: [
  # All of these a returned when the grid is changed
  # The number of balls in the game arena
  { name: "balls" shape: [1], dtype: INT32 },
  # The number of guessed balls made by the agent
  { name: "guesses" shape: [1], dtype: INT32 },
  # 1 if the guesses are wrong, 0 otherwise
  { name: "wrong" shape: [1], dtype: INT32 },
  # The number of lasers in the grid
  { name: "lasers" shape: [1], dtype: INT32 },
  # The grid cells:
  # - In the arena: 'G'=guessed ball ' '=empty
  # - In the range: [0-9]=the number of lasers, 'H'=beam hit, 'R'=beam reflected,
  # '?' unknown
  # - ' ' for the corners
  { name: "grid" shape: [12, 12], dtype: STRING_U1 }
]
